// <auto-generated />
using System;
using Landbridge.ControlPlane;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Landbridge.ControlPlane.Migrations
{
    [DbContext(typeof(LandbridgeDbContext))]
    partial class LandbridgeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Landbridge.ControlPlane.Auth.CredentialRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("EvictedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evicted_at");

                    b.Property<Guid?>("EvictedByHuman")
                        .HasColumnType("uuid")
                        .HasColumnName("evicted_by_human");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("HumanId")
                        .HasColumnType("uuid")
                        .HasColumnName("human_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<Guid?>("MachineId")
                        .HasColumnType("uuid")
                        .HasColumnName("machine_id");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean")
                        .HasColumnName("revoked");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid?>("WorkerInstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_instance_id");

                    b.HasKey("Id")
                        .HasName("pk_credentials");

                    b.HasIndex("MachineId")
                        .HasDatabaseName("ix_credentials_machine_id");

                    b.HasIndex("TeamId")
                        .IsUnique()
                        .HasDatabaseName("ix_credentials_one_live_lead_per_team")
                        .HasFilter("kind = 'Lead' AND revoked = false");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_credentials_token_hash");

                    b.ToTable("credentials", (string)null);
                });

            modelBuilder.Entity("Landbridge.ControlPlane.Auth.LeadEventRow", b =>
                {
                    b.Property<long>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("seq");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Seq"));

                    b.Property<Guid?>("HumanId")
                        .HasColumnType("uuid")
                        .HasColumnName("human_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid?>("PriorHumanId")
                        .HasColumnType("uuid")
                        .HasColumnName("prior_human_id");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Seq")
                        .HasName("pk_lead_events");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_lead_events_team_id");

                    b.ToTable("lead_events", (string)null);
                });

            modelBuilder.Entity("Landbridge.ControlPlane.Auth.LeadMachineBindingRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("BoundAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bound_at");

                    b.Property<Guid>("HumanId")
                        .HasColumnType("uuid")
                        .HasColumnName("human_id");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("uuid")
                        .HasColumnName("machine_id");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean")
                        .HasColumnName("revoked");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.HasKey("Id")
                        .HasName("pk_lead_machine_bindings");

                    b.HasIndex("HumanId")
                        .IsUnique()
                        .HasDatabaseName("ix_lead_machine_bindings_one_live_per_human")
                        .HasFilter("revoked = false");

                    b.HasIndex("MachineId")
                        .IsUnique()
                        .HasDatabaseName("ix_lead_machine_bindings_one_live_per_machine")
                        .HasFilter("revoked = false");

                    b.ToTable("lead_machine_bindings", (string)null);
                });

            modelBuilder.Entity("Landbridge.ControlPlane.Auth.MachineRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("EnrolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrolled_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Os")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("os");

                    b.Property<string>("PermissionLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("permission_level");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("purpose");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean")
                        .HasColumnName("revoked");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.HasKey("Id")
                        .HasName("pk_machines");

                    b.ToTable("machines", (string)null);
                });

            modelBuilder.Entity("Landbridge.ControlPlane.Auth.OAuthAuthorizationCodeRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_id");

                    b.Property<string>("CodeChallenge")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code_challenge");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("RedirectUri")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("redirect_uri");

                    b.Property<string>("Resource")
                        .HasColumnType("text")
                        .HasColumnName("resource");

                    b.Property<string>("Scope")
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.HasKey("Id")
                        .HasName("pk_oauth_authorization_codes");

                    b.HasIndex("CodeHash")
                        .IsUnique()
                        .HasDatabaseName("ix_oauth_authorization_codes_code_hash");

                    b.ToTable("oauth_authorization_codes", (string)null);
                });

            modelBuilder.Entity("Landbridge.ControlPlane.Auth.RelayGrantRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ConsumerInstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("consumer_instance_id");

                    b.Property<Guid?>("ConsumerSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("consumer_session_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("ForwardId")
                        .HasColumnType("uuid")
                        .HasColumnName("forward_id");

                    b.Property<string>("GrantHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grant_hash");

                    b.Property<Guid>("ProducerSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("producer_session_id");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean")
                        .HasColumnName("revoked");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_name");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<DateTimeOffset?>("UsedByConsumerAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_by_consumer_at");

                    b.Property<DateTimeOffset?>("UsedByProducerAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_by_producer_at");

                    b.HasKey("Id")
                        .HasName("pk_relay_grants");

                    b.HasIndex("ForwardId")
                        .IsUnique()
                        .HasDatabaseName("ix_relay_grants_forward_id");

                    b.HasIndex("GrantHash")
                        .IsUnique()
                        .HasDatabaseName("ix_relay_grants_grant_hash");

                    b.HasIndex("ProducerSessionId")
                        .HasDatabaseName("ix_relay_grants_producer_session_id");

                    b.ToTable("relay_grants", (string)null);
                });

            modelBuilder.Entity("Landbridge.ControlPlane.PreviewMappingRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthPolicy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth_policy");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("LabelHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label_hash");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_name");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id")
                        .HasName("pk_preview_mappings");

                    b.HasIndex("LabelHash")
                        .IsUnique()
                        .HasDatabaseName("ix_preview_mappings_label_hash");

                    b.ToTable("preview_mappings", (string)null);
                });

            modelBuilder.Entity("Landbridge.ControlPlane.RegisteredServiceRow", b =>
                {
                    b.Property<long>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("seq");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Seq"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Seq")
                        .HasName("pk_registered_services");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_registered_services_session_id");

                    b.HasIndex("TeamId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_registered_services_team_id_name");

                    b.ToTable("registered_services", (string)null);
                });

            modelBuilder.Entity("Landbridge.ControlPlane.SessionEventRow", b =>
                {
                    b.Property<long>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("seq");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Seq"));

                    b.Property<string>("AuthErrorCode")
                        .HasColumnType("text")
                        .HasColumnName("auth_error_code");

                    b.Property<string>("AuthMissingScope")
                        .HasColumnType("text")
                        .HasColumnName("auth_missing_scope");

                    b.Property<string>("AuthOperation")
                        .HasColumnType("text")
                        .HasColumnName("auth_operation");

                    b.Property<string>("AuthTarget")
                        .HasColumnType("text")
                        .HasColumnName("auth_target");

                    b.Property<string>("Detail")
                        .HasColumnType("text")
                        .HasColumnName("detail");

                    b.Property<string>("FromState")
                        .HasColumnType("text")
                        .HasColumnName("from_state");

                    b.Property<string>("InputKind")
                        .HasColumnType("text")
                        .HasColumnName("input_kind");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("LivenessReason")
                        .HasColumnType("text")
                        .HasColumnName("liveness_reason");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PermissionAnswerer")
                        .HasColumnType("text")
                        .HasColumnName("permission_answerer");

                    b.Property<string>("PermissionVerdict")
                        .HasColumnType("text")
                        .HasColumnName("permission_verdict");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("SubagentId")
                        .HasColumnType("text")
                        .HasColumnName("subagent_id");

                    b.Property<string>("SubagentParentId")
                        .HasColumnType("text")
                        .HasColumnName("subagent_parent_id");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<string>("ToState")
                        .HasColumnType("text")
                        .HasColumnName("to_state");

                    b.HasKey("Seq")
                        .HasName("pk_session_events");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_session_events_session_id");

                    b.ToTable("session_events", (string)null);
                });

            modelBuilder.Entity("Landbridge.ControlPlane.SessionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnName("attempt");

                    b.Property<DateTimeOffset?>("BlockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("blocked_at");

                    b.Property<string>("CompletionProvenance")
                        .HasColumnType("text")
                        .HasColumnName("completion_provenance");

                    b.Property<Guid?>("ContinuesSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("continues_session_id");

                    b.Property<Guid?>("CurrentInstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_instance_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Health")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("health");

                    b.Property<string>("HarnessSessionRef")
                        .HasColumnType("text")
                        .HasColumnName("harness_session_ref");

                    b.Property<bool>("Hidden")
                        .HasColumnType("boolean")
                        .HasColumnName("hidden");

                    b.Property<int>("InfrastructureRequeueLimit")
                        .HasColumnType("integer")
                        .HasColumnName("infrastructure_requeue_limit");

                    b.Property<int>("InfrastructureRequeues")
                        .HasColumnType("integer")
                        .HasColumnName("infrastructure_requeues");

                    b.Property<string>("InputAnswer")
                        .HasColumnType("text")
                        .HasColumnName("input_answer");

                    b.Property<string>("InputKind")
                        .HasColumnType("text")
                        .HasColumnName("input_kind");

                    b.Property<string>("InputQuestion")
                        .HasColumnType("text")
                        .HasColumnName("input_question");

                    b.Property<string>("LastRequeueReason")
                        .HasColumnType("text")
                        .HasColumnName("last_requeue_reason");

                    b.Property<DateTimeOffset?>("LastMessageClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_message_closed_at");

                    b.Property<Guid?>("LastMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_message_id");

                    b.Property<string>("LastMessageTerminal")
                        .HasColumnType("text")
                        .HasColumnName("last_message_terminal");

                    b.Property<Guid?>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<DateTimeOffset?>("MessageOpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("message_opened_at");

                    b.Property<DateTimeOffset?>("MessagePulledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("message_pulled_at");

                    b.Property<string>("MessageState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_state");

                    b.Property<string>("MessageVerdict")
                        .HasColumnType("text")
                        .HasColumnName("message_verdict");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("namespace");

                    b.Property<string>("OccupancyDesired")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("occupancy_desired");

                    b.Property<string>("OccupancyObserved")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("occupancy_observed");

                    b.Property<string>("OnMachineGone")
                        .HasColumnType("text")
                        .HasColumnName("on_machine_gone");

                    b.Property<string>("PendingSpawn")
                        .HasColumnType("text")
                        .HasColumnName("pending_spawn");

                    b.Property<string>("ParkMachine")
                        .HasColumnType("text")
                        .HasColumnName("park_machine");

                    b.Property<DateTimeOffset?>("PermissionEscalatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("permission_escalated_at");

                    b.Property<string>("PermissionEscalationReason")
                        .HasColumnType("text")
                        .HasColumnName("permission_escalation_reason");

                    b.Property<string>("PermissionOptionId")
                        .HasColumnType("text")
                        .HasColumnName("permission_option_id");

                    b.Property<string>("PermissionOptions")
                        .HasColumnType("text")
                        .HasColumnName("permission_options");

                    b.Property<string>("PermissionTool")
                        .HasColumnType("text")
                        .HasColumnName("permission_tool");

                    b.Property<string>("PermissionVerdict")
                        .HasColumnType("text")
                        .HasColumnName("permission_verdict");

                    b.Property<string>("PreferredMachine")
                        .HasColumnType("text")
                        .HasColumnName("preferred_machine");

                    b.Property<string>("Profile")
                        .HasColumnType("text")
                        .HasColumnName("profile");

                    b.Property<bool>("PullRedelivered")
                        .HasColumnType("boolean")
                        .HasColumnName("pull_redelivered");

                    b.Property<bool>("ReportUnread")
                        .HasColumnType("boolean")
                        .HasColumnName("report_unread");

                    b.Property<string>("ResultReference")
                        .HasColumnType("text")
                        .HasColumnName("result_reference");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<string>("TraceContext")
                        .HasColumnType("text")
                        .HasColumnName("trace_context");

                    b.Property<int>("VerificationFailures")
                        .HasColumnType("integer")
                        .HasColumnName("verification_failures");

                    b.Property<int>("VerificationRetryLimit")
                        .HasColumnType("integer")
                        .HasColumnName("verification_retry_limit");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid?>("WorkDirSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_dir_session_id");

                    b.Property<string>("WorkerReport")
                        .HasColumnType("text")
                        .HasColumnName("worker_report");

                    b.HasKey("Id")
                        .HasName("pk_sessions");

                    b.HasIndex("Namespace")
                        .IsUnique()
                        .HasDatabaseName("ix_sessions_namespace");

                    b.HasIndex("State", "Profile")
                        .HasDatabaseName("ix_sessions_state_profile")
                        .HasFilter("state = 'Submitted'");

                    b.HasIndex("Profile", "OccupancyDesired", "OccupancyObserved", "Health")
                        .HasDatabaseName("ix_sessions_profile_occupancy_desired_occupancy_observed_health")
                        .HasFilter("occupancy_desired = 'Running' AND health = 'Ok' AND hidden = false AND occupancy_observed IN ('None','OnDisk') AND current_instance_id IS NULL AND pending_spawn IN ('New','Load')");

                    b.HasIndex("TeamId", "MessageId")
                        .HasDatabaseName("ix_sessions_team_id_message_id");

                    b.HasIndex("TeamId", "LastMessageId")
                        .HasDatabaseName("ix_sessions_team_id_last_message_id");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("Landbridge.ControlPlane.SessionUsageRow", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Model")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("model");

                    b.Property<long>("CacheReadTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("cache_read_tokens");

                    b.Property<long>("CacheWriteTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("cache_write_tokens");

                    b.Property<decimal?>("CostUsd")
                        .HasColumnType("numeric")
                        .HasColumnName("cost_usd");

                    b.Property<long>("InputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("input_tokens");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("output_tokens");

                    b.Property<long?>("ReasoningOutputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("reasoning_output_tokens");

                    b.Property<DateTimeOffset>("ReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reported_at");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("SessionId", "Model")
                        .HasName("pk_session_usage");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_session_usage_team_id");

                    b.ToTable("session_usage", (string)null);
                });

            modelBuilder.Entity("Landbridge.ControlPlane.TeamForwardUsageRow", b =>
                {
                    b.Property<Guid>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<long>("ForwardedBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("forwarded_bytes");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TeamId")
                        .HasName("pk_team_forward_usage");

                    b.ToTable("team_forward_usage", (string)null);
                });

            modelBuilder.Entity("Landbridge.ControlPlane.WorkerInstanceRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MachineId")
                        .HasColumnType("text")
                        .HasColumnName("machine_id");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean")
                        .HasColumnName("revoked");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id")
                        .HasName("pk_worker_instances");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_worker_instances_session_id");

                    b.ToTable("worker_instances", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
